version: '3.7'

services:

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=globotech
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    container_name: globotech
    ports:
      - 3333:3333
    volumes:
      - .:/usr/apps
    links: 
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local 
