version: '3.7'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: globotech
    networks:
      - jsons-food
networks:
  jsons-food:

